# Generated by Django 5.1.6 on 2025-02-15 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yum_app', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('age', models.PositiveIntegerField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('bmi', models.FloatField(editable=False, null=True)),
                ('maintenance_calories', models.FloatField(blank=True, null=True)),
                ('recommended_carbs', models.FloatField(blank=True, null=True)),
                ('recommended_fats', models.FloatField(blank=True, null=True)),
                ('recommended_protein', models.FloatField(blank=True, null=True)),
                ('recommended_recipes', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
