# Generated by Django 5.1.6 on 2025-02-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yum_app', '0003_userhealthprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhealthprofile',
            name='recommended_recipes',
        ),
    ]
